cover: assets/images/background.png
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Guruvansh Muvel
email: s4mc0d3@gmail.com
description: Website of Guruvansh Muvel
keywords: Guruvansh, Muvel, s4mc0d3,  security, developer, geek, programmer, github
baseurl: ""
url: http://guruvansh.com/
name: s4m c0d3\'s blog
author:
  name: Guruvansh Muvel
  email: s4mc0d3@gmail.com
