github_url: https://github.com/Samc0d3
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf
sitemap_url: /sitemap.xml
